POST http://localhost:3000/products
Content-Type: application/json

{
    "idUser": "61b62db34c104c7a696511f0",
    "state": "En Attente",
    "title": "iPhone 12 128go",
    "description": "iPhone 12 128go parfait etat",
    "price": 969,
    "idCategory": "61b37aff3cb6b131c8aa9a4a",
    "address": "Clos chappel au champ 43 Woluwe"
    }

###

GET http://localhost:3000/products
Content-Type: application/json
###

GET http://localhost:3000/products/61b32cbe077d6f98f1d4130f
Content-Type: application/json
###

GET http://localhost:3000/products/product-images/banane8cfaff50-d549-4ba4-af3e-2cf6acc3d6c1.jpg
Content-Type: application/json
###
DELETE  http://localhost:3000/products/61b32da6077d6f98f1d41319
Content-Type: application/json
###

PATCH http://localhost:3000/products/61b32da6077d6f98f1d41319
Content-Type: application/json

{
    "idUser": "61af4d49b82ce6de16f8fa4c",
    "state": "Vendre",
    "title": "Tablier labo",
    "description": "Tablier labo en or massif pour BLOC 7 - CHIMIE",
    "price": "255",
    "idCategory": "55"
}

###
GET http://localhost:3000/products?sort=DESC&search=2
Content-Type: application/json



###
GET   http://localhost:3000/products/productsUser/61b62db34c104c7a696511f0
Content-Type: application/json

{
    "idUser": "61b62db34c104c7a696511f0"
}